// AUTO-GENERATED by scripts/check-dialogue-audio.mjs — do not hand-edit.
// Re-run that script after dropping a new WAV into public/audio/dialogue/
// and re-render. true = real recorded speech detected (mean volume above
// -50dB); false = silent placeholder or missing file,
// meaning the composition falls back to the original source narration for
// that line's time range.
export const DIALOGUE_AUDIO_AVAILABLE: Record<string, boolean> = {
  "female-replacement-01.wav": false,
  "female-replacement-02.wav": false,
  "female-replacement-03.wav": false,
  "female-replacement-04.wav": false,
  "female-replacement-05.wav": false,
  "female-replacement-06.wav": false,
  "female-replacement-07.wav": false
};
