// Edit Decision List for "Nee Pona Pinne" — every source in/out, speed, and
// transition value used to build the final timeline. Generated from an
// automated frame-difference scene-boundary scan of the source master
// (see the report delivered alongside this project for methodology and
// tool limitations), then hand-verified against the locked story table in
// the edit spec. All values are editable here without touching any JSX.
//
// detectionConfidence meanings:
//  - "anchor": frame 0, the guaranteed start of the film.
//  - "confirmed": boundary matches a strong (diff>45), visually spot-checked
//    scene-change spike AND falls on the exact regular ~10s rhythm the
//    first 13 source clips were generated at.
//  - "snapped(diff=N)": a real scene-change spike was found near the
//    running nominal 9.964s-per-scene grid position and used instead of
//    the raw nominal estimate.
//  - "estimated": no clear spike was found near the nominal grid position
//    within the search window; the nominal grid value was kept as-is.
//    These are the scenes most worth reviewing frame-by-frame before
//    trusting completely — see the review-pass contact sheets.
export type Phase = "lonely" | "happy" | "breakup" | "reunion" | "resolution";

export type TransitionType =
  | "hard_cut"
  | "hard_cut_downbeat"
  | "hard_cut_lcut"
  | "hard_cut_grade_shift"
  | "hard_reset"
  | "vehicle_wipe"
  | "occlusion_wipe"
  | "ambience_jcut"
  | "match_cut_blend4"
  | "match_glass"
  | "graphic_match_clink"
  | "warm_dissolve6"
  | "match_hands"
  | "color_temp_bridge6"
  | "body_turn_match"
  | "gaze_action_jcut4"
  | "match_cut_soft4"
  | "jl_cut"
  | "body_turn_cut"
  | "fade_black_10";

export interface EdlRow {
  scene: number;
  outputIn: string;
  outputOut: string;
  outputDurationS: number;
  purpose: string;
  treatment: string;
  phase: Phase;
  transitionIn: TransitionType;
  sourceInS: number;
  sourceOutS: number;
  speed: number;
  freezeFrames: number;
  detectionConfidence: string;
  notes: string;
}

export const EDL: EdlRow[] = [
  {
    scene: 1,
    outputIn: "00:00",
    outputOut: "00:07",
    outputDurationS: 7.0,
    purpose: "Arun alone on the empty road",
    treatment: "Start on purposeful walking; remove camera-start settling",
    phase: "lonely",
    transitionIn: "hard_cut",
    sourceInS: 0.0,
    sourceOutS: 6.195,
    speed: 0.92,
    freezeFrames: 8,
    detectionConfidence: "anchor",
    notes: "source shorter than needed even at 0.92x floor; 8-frame end freeze added (documented exception, source scene is the shortest in the film); boundary confidence: anchor",
  },
  {
    scene: 2,
    outputIn: "00:07",
    outputOut: "00:14",
    outputDurationS: 7.0,
    purpose: "Arun sees Maya as memory",
    treatment: "Preserve first recognition and Maya's strongest natural smile",
    phase: "lonely",
    transitionIn: "vehicle_wipe",
    sourceInS: 6.6,
    sourceOutS: 14.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 3,
    outputIn: "00:14",
    outputOut: "00:21",
    outputDurationS: 7.0,
    purpose: "Passing vehicle clears; Maya is gone",
    treatment: "Use vehicle as an in-camera wipe; end on empty space",
    phase: "lonely",
    transitionIn: "hard_cut_downbeat",
    sourceInS: 16.6,
    sourceOutS: 24.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 4,
    outputIn: "00:21",
    outputOut: "00:28",
    outputDurationS: 7.0,
    purpose: "Sleepless bedroom",
    treatment: "Keep restrained turn/eye movement; remove dead hold",
    phase: "lonely",
    transitionIn: "ambience_jcut",
    sourceInS: 26.6,
    sourceOutS: 34.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 5,
    outputIn: "00:28",
    outputOut: "00:35",
    outputDurationS: 7.0,
    purpose: "Familiar street with empty space beside Arun",
    treatment: "Keep lateral walking continuity",
    phase: "lonely",
    transitionIn: "match_cut_blend4",
    sourceInS: 36.6,
    sourceOutS: 44.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 6,
    outputIn: "00:35",
    outputOut: "00:42",
    outputDurationS: 7.0,
    purpose: "Maya now walks beside him in memory",
    treatment: "Match direction and scale to Scene 05",
    phase: "happy",
    transitionIn: "hard_cut",
    sourceInS: 46.6,
    sourceOutS: 54.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 7,
    outputIn: "00:42",
    outputOut: "00:49",
    outputDurationS: 7.0,
    purpose: "Maya's laugh",
    treatment: "Choose the most stable, genuine expression; avoid warped tail",
    phase: "happy",
    transitionIn: "occlusion_wipe",
    sourceInS: 56.6,
    sourceOutS: 64.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 8,
    outputIn: "00:49",
    outputOut: "00:56",
    outputDurationS: 7.0,
    purpose: "Back to present; Arun alone",
    treatment: "Use a foreground wipe or hard reveal from memory to present",
    phase: "lonely",
    transitionIn: "hard_cut",
    sourceInS: 66.6,
    sourceOutS: 74.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 9,
    outputIn: "00:56",
    outputOut: "01:03",
    outputDurationS: 7.0,
    purpose: "First breakup fragment; Maya walks away",
    treatment: "Preserve separation and Arun's stillness",
    phase: "breakup",
    transitionIn: "hard_cut_lcut",
    sourceInS: 76.6,
    sourceOutS: 84.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 10,
    outputIn: "01:03",
    outputOut: "01:10",
    outputDurationS: 7.0,
    purpose: "She does not turn back",
    treatment: "Cut redundant walking; keep hesitation plus continuation",
    phase: "breakup",
    transitionIn: "hard_cut",
    sourceInS: 86.6,
    sourceOutS: 94.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 11,
    outputIn: "01:10",
    outputOut: "01:17",
    outputDurationS: 7.0,
    purpose: "Arun's hand cannot hold her",
    treatment: "Prioritize hand release and restrained reaction",
    phase: "lonely",
    transitionIn: "hard_reset",
    sourceInS: 96.6,
    sourceOutS: 104.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 12,
    outputIn: "01:17",
    outputOut: "01:24",
    outputDurationS: 7.0,
    purpose: "Tea shop: one tea, two people",
    treatment: "Open on glass placement; retain natural playfulness",
    phase: "happy",
    transitionIn: "match_glass",
    sourceInS: 106.6,
    sourceOutS: 114.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 13,
    outputIn: "01:24",
    outputOut: "01:31",
    outputDurationS: 7.0,
    purpose: "Tea fight micro-montage",
    treatment: "Use clean internal cuts if already present; cut on hand/glass motion",
    phase: "happy",
    transitionIn: "graphic_match_clink",
    sourceInS: 116.6,
    sourceOutS: 124.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "confirmed",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: confirmed",
  },
  {
    scene: 14,
    outputIn: "01:31",
    outputOut: "01:38",
    outputDurationS: 7.0,
    purpose: "Rain at bus stop",
    treatment: "Begin with raindrop/pavement where available; preserve intimate gesture",
    phase: "happy",
    transitionIn: "hard_cut",
    sourceInS: 126.6,
    sourceOutS: 134.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=55)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=55)",
  },
  {
    scene: 15,
    outputIn: "01:38",
    outputOut: "01:45",
    outputDurationS: 7.0,
    purpose: "Couple runs into rain",
    treatment: "Use the cleanest energetic action; avoid slow generated tail",
    phase: "happy",
    transitionIn: "hard_cut",
    sourceInS: 136.6,
    sourceOutS: 144.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=47)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=47)",
  },
  {
    scene: 16,
    outputIn: "01:45",
    outputOut: "01:52",
    outputDurationS: 7.0,
    purpose: "Rain intimacy / shared movement",
    treatment: "Preserve physical continuity and identity",
    phase: "happy",
    transitionIn: "warm_dissolve6",
    sourceInS: 147.2,
    sourceOutS: 154.76,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=21)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=21)",
  },
  {
    scene: 17,
    outputIn: "01:52",
    outputOut: "01:59",
    outputDurationS: 7.0,
    purpose: "Warm relationship memory",
    treatment: "Select the clearest complete action, not a prolonged pose",
    phase: "happy",
    transitionIn: "hard_cut",
    sourceInS: 157.6,
    sourceOutS: 165.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=60)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=60)",
  },
  {
    scene: 18,
    outputIn: "01:59",
    outputOut: "02:06",
    outputDurationS: 7.0,
    purpose: "Simple everyday love",
    treatment: "Keep ordinary affectionate behavior; remove repeated gesture",
    phase: "happy",
    transitionIn: "match_hands",
    sourceInS: 167.6,
    sourceOutS: 175.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "estimated",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: estimated",
  },
  {
    scene: 19,
    outputIn: "02:06",
    outputOut: "02:13",
    outputDurationS: 7.0,
    purpose: "Simple flower/note; love without luxury",
    treatment: "Feature flower, reaction, touch; cut before anatomy drifts",
    phase: "happy",
    transitionIn: "color_temp_bridge6",
    sourceInS: 178.6,
    sourceOutS: 186.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=80)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=80)",
  },
  {
    scene: 20,
    outputIn: "02:13",
    outputOut: "02:20",
    outputDurationS: 7.0,
    purpose: "Last conversation",
    treatment: "Preserve Arun steps forward / Maya steps back / she turns",
    phase: "breakup",
    transitionIn: "body_turn_match",
    sourceInS: 189.7,
    sourceOutS: 197.26,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=66)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=66)",
  },
  {
    scene: 21,
    outputIn: "02:20",
    outputOut: "02:27",
    outputDurationS: 7.0,
    purpose: "Maya leaves; emotional focus stays on Arun",
    treatment: "Use growing empty space; cut duplicated walk cycle",
    phase: "breakup",
    transitionIn: "gaze_action_jcut4",
    sourceInS: 199.6,
    sourceOutS: 207.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=36)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=36)",
  },
  {
    scene: 22,
    outputIn: "02:27",
    outputOut: "02:34",
    outputDurationS: 7.0,
    purpose: "Arun discovers the old photograph",
    treatment: "Preserve drawer/photo/eyeline/rack-focus progression",
    phase: "lonely",
    transitionIn: "match_cut_soft4",
    sourceInS: 209.1,
    sourceOutS: 216.66,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=25)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=25)",
  },
  {
    scene: 23,
    outputIn: "02:34",
    outputOut: "02:41",
    outputDurationS: 7.0,
    purpose: "Every memory at once",
    treatment: "Make this the fastest montage; retain established memories only",
    phase: "happy",
    transitionIn: "hard_cut_grade_shift",
    sourceInS: 220.6,
    sourceOutS: 228.16,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=65)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=65)",
  },
  {
    scene: 24,
    outputIn: "02:41",
    outputOut: "02:48",
    outputDurationS: 7.0,
    purpose: "Present-day Maya appears with another man",
    treatment: "Match past Maya to present Maya; reveal Arun after recognition",
    phase: "reunion",
    transitionIn: "jl_cut",
    sourceInS: 230.0,
    sourceOutS: 236.9,
    speed: 0.9857,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=42)",
    notes: "boundary confidence: snapped(diff=42)",
  },
  {
    scene: 25,
    outputIn: "02:48",
    outputOut: "02:54",
    outputDurationS: 6.0,
    purpose: "Arun accepts that she is happy",
    treatment: "Keep breath, lowered eyes, final look, tiny bittersweet smile",
    phase: "reunion",
    transitionIn: "body_turn_cut",
    sourceInS: 237.6,
    sourceOutS: 244.08,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "snapped(diff=70)",
    notes: "speed clamped to 1.08x ceiling; extra source trimmed from tail; boundary confidence: snapped(diff=70)",
  },
  {
    scene: 26,
    outputIn: "02:54",
    outputOut: "02:56.352",
    outputDurationS: 2.352,
    purpose: "Arun walks forward; resolution",
    treatment: "Use the strongest rear walking moment; he never looks back",
    phase: "resolution",
    transitionIn: "fade_black_10",
    sourceInS: 245.5,
    sourceOutS: 248.04,
    speed: 1.08,
    freezeFrames: 0,
    detectionConfidence: "corrected",
    notes: "IMPORTANT CORRECTION: the diff=124 spike at 249.2s (originally used as this scene's boundary) is NOT a story-scene cut — it is the cut from live-action into the source master's OWN baked-in end-credit cards (\"A FILM BY ESWARAN\" / \"AN ESHAN PRODUCTION\" / \"MUSIC CREATED WITH GOOGLE FLOW MUSIC 2026\", ~249.2-259.07s, confirmed by direct frame inspection). The original range [256.4, 258.95] was therefore pure black title-card footage, not Arun walking. Re-pointed to the actual rear-walking shot at 245.5-248.04s (confirmed clean, ends just before the credit fade-in begins around 248.7s). Since the source already bakes in its own credit sequence with near-identical wording to the brief's requested FinalCredits text, FinalCredits.tsx renders as a text overlay rather than reusing the source's black card footage, which has no room left in the locked 2.352s slot.",
  },
];
